# Generated by Django 3.1.7 on 2021-08-26 12:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_options', models.CharField(choices=[('Choose', 'Choose'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='Choose', max_length=50)),
                ('module_numbering', models.CharField(max_length=5)),
                ('module_numbering_title', models.CharField(max_length=100)),
                ('module_subtitle_numbering', models.CharField(max_length=5)),
                ('module_numbering_subtitle', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('drive_link', models.CharField(default='#', max_length=250)),
            ],
        ),
    ]
